### PR TITLE
Fix the RSA key size check

### LINKED ISSUE #30: RSA256 implementation wrongfully requires exactly 2048 bit keys; should be >= 2048
See more info on why here: https://crypto.stackexchange.com/questions/95878/does-the-signature-length-of-rs256-depend-on-the-size-of-the-rsa-key-used-for-si

Is short, RSA256 means 256-byte hashes, not keys.

### PR DESCRIPTION
**Pull request by MOZGIII**
Fixes #30

### CODE REVIEW

**Review by neoeinstein — APPROVED** [review]
Thanks for this. It's good to have an allowance for larger keys.

**Comment by neoeinstein** [comment]
The linter failure is due to a new lint in a newer version of the Rust compiler. I'll fix that separately.

**Comment by MOZGIII** [comment]
Let's merge then!

**Pull request merged**
